In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Training Dataset
dataset_train = pd.read_csv("train.csv")
dataset_train["Age"].fillna(value=29.699118,axis = 0, inplace = True)


x_train = dataset_train.loc[:,["Pclass","Sex","Age","SibSp","Parch","Fare"]].values
y_train = dataset_train.iloc[:,1].values

#Testing Data
dataset_test = pd.read_csv("test.csv")
dataset_test["Age"].fillna(value=29.699118,axis = 0, inplace = True)
x_test = dataset_test.loc[:,["Pclass","Sex","Age","SibSp","Parch","Fare"]].values
y_test = dataset_test.iloc[:,1].values


In [3]:
x_train[0]

array([3, 'male', 22.0, 1, 0, 7.25], dtype=object)

In [4]:
# OneHot Encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
#ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[-1])], remainder = 'passthrough')

x_train = ct.fit_transform(x_train)
x_test = ct.transform(x_test)
x_train[0]

array([0.0, 1.0, 3, 22.0, 1, 0, 7.25], dtype=object)

In [5]:
for i in x_train:
    print(i)

[0.0 1.0 3 22.0 1 0 7.25]
[1.0 0.0 1 38.0 1 0 71.2833]
[1.0 0.0 3 26.0 0 0 7.925]
[1.0 0.0 1 35.0 1 0 53.1]
[0.0 1.0 3 35.0 0 0 8.05]
[0.0 1.0 3 29.699118 0 0 8.4583]
[0.0 1.0 1 54.0 0 0 51.8625]
[0.0 1.0 3 2.0 3 1 21.075]
[1.0 0.0 3 27.0 0 2 11.1333]
[1.0 0.0 2 14.0 1 0 30.0708]
[1.0 0.0 3 4.0 1 1 16.7]
[1.0 0.0 1 58.0 0 0 26.55]
[0.0 1.0 3 20.0 0 0 8.05]
[0.0 1.0 3 39.0 1 5 31.275]
[1.0 0.0 3 14.0 0 0 7.8542]
[1.0 0.0 2 55.0 0 0 16.0]
[0.0 1.0 3 2.0 4 1 29.125]
[0.0 1.0 2 29.699118 0 0 13.0]
[1.0 0.0 3 31.0 1 0 18.0]
[1.0 0.0 3 29.699118 0 0 7.225]
[0.0 1.0 2 35.0 0 0 26.0]
[0.0 1.0 2 34.0 0 0 13.0]
[1.0 0.0 3 15.0 0 0 8.0292]
[0.0 1.0 1 28.0 0 0 35.5]
[1.0 0.0 3 8.0 3 1 21.075]
[1.0 0.0 3 38.0 1 5 31.3875]
[0.0 1.0 3 29.699118 0 0 7.225]
[0.0 1.0 1 19.0 3 2 263.0]
[1.0 0.0 3 29.699118 0 0 7.8792]
[0.0 1.0 3 29.699118 0 0 7.8958]
[0.0 1.0 1 40.0 0 0 27.7208]
[1.0 0.0 1 29.699118 1 0 146.5208]
[1.0 0.0 3 29.699118 0 0 7.75]
[0.0 1.0 2 66.0 0 0 10.5]
[0.0 1.0 1 28.0 1 0 82.1708]
[0.0 1

In [6]:
#Standardising the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)

In [7]:
from sklearn.tree import  DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtc.fit(x_train, y_train)
y_pred = dtc.predict(x_test)

In [8]:
from sklearn.ensemble import RandomForestRegressor
regsr = RandomForestRegressor(n_estimators=10, random_state=0)
regsr.fit(x_train,y_train)
y_pred2 = regsr.predict(x_test)

In [9]:
#Making confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

y_pred2list = []
for x in regsr.predict(x_test):
    if x > 0.2:
        y_pred2list.append(1)
    else:
        y_pred2list.append(0)
cm2 = confusion_matrix(y_test, np.array(y_pred2list))
print(cm)
print(accuracy_score(y_test,y_pred)*100)
print(accuracy_score(y_test,np.array(y_pred2list))*100)

[[  0   0   0   0]
 [ 18  89   0   0]
 [ 17  76   0   0]
 [ 34 184   0   0]]
21.291866028708135
21.052631578947366
