# Numpy Documentation

In [1]:
import numpy as np

## *Creating a numpy array using python list*

In [2]:
# Creating a  1-D numpy array
myarr = np.array([2,3,4,5])
print(myarr.dtype)
print(type(myarr))    #NumPy’s array class is called ndarray
myarr

int32
<class 'numpy.ndarray'>


array([2, 3, 4, 5])

In [3]:
# Creating a 2-D numpy array
myarr2 = np.array([[2,3,4,5],[6,7,8,9]])
print(myarr.dtype)
myarr2

int32


array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [4]:
#Some function of ndarray----
print(myarr.ndim)         #returns dimension of the ndarray
print(myarr.shape)        #returns shape as Rows X columns
print(myarr.dtype)        #returns type of value contained such as int8,int16,int32,int64, or as float8,float16....float64
print(myarr.itemsize)     #returns item size of th ndarray
print(myarr.data)         #returns memory address of the ndarray stored.

1
(4,)
int32
4


### -->Using dtype argument to alter the dtype of data

In [5]:
myarr3 = np.array([[1,2],[3,4]],dtype = complex)
print(myarr3.dtype)
myarr3

complex128


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [6]:
myarr4 = np.zeros(3)
myarr4

array([0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

## *Arithmetic with NumPy Arrays*

In [12]:
myarr4 = np.array([[1,2,3],[4,5,6]])
myarr4_sq = myarr4*myarr4
myarr4_sq

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
myarr5 = np.array([[2,3,4],[5,6,7]])
sum_myarr = myarr4+myarr5
sum_myarr

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [14]:
sub = myarr4 - myarr5
sub

array([[-1, -1, -1],
       [-1, -1, -1]])

In [15]:
1/myarr4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [17]:
# Slicing the 3d array
myarr3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
myarr3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# selecting the first row
print("first row",myarr3d[0])
#selecting the sec row 
print("sec row",myarr3d[1])
#selecting the third row
print("third row",myarr3d[2])


first row [1 2 3]
sec row [4 5 6]
third row [7 8 9]


In [34]:
# selecting columns
print("1st col", myarr3d[:,:1])
print("2nd col", myarr3d[:,1:2])
print("3rd col", myarr3d[:,2:3])


1st col [[1]
 [4]
 [7]]
2nd col [[2]
 [5]
 [8]]
3rd col [[3]
 [6]
 [9]]


In [35]:
#selecting two vertical cols
myarr3d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
myarr3d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [47]:
myarr3d[:2,:2]

array([[1, 2],
       [4, 5]])

In [49]:
myarr3d[2:,2:]

array([[9]])

## Pseudorandom Number Generation

In [51]:
samples = np.random.standard_normal(size=(4, 4))
samples

array([[-0.49065221, -1.38088471, -1.33493431,  0.0396653 ],
       [ 1.73063151,  0.27625077,  0.91006528,  0.41315968],
       [-0.22108598,  0.10005844,  0.93928527, -0.96908012],
       [ 1.46018922, -1.22303318, -0.25171057,  0.75833563]])